language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - cat /etc/apt/sources.list
    - sudo apt-get update
    - sudo apt-get install --force-yes -qq p7zip openjdk-7-jdk ant lib32z1-dev lib32stdc++6  #lib32* are needed by Android SDK
    - sudo update-alternatives --display java
    - sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
    - sh -e /etc/init.d/xvfb start
script:
    - export WORKDIR=$PWD
    - echo $PWD
    - source path.env
    - wget -c https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
    - extract-qt-installer --list-packages qt-unified-linux-x64-online.run
    - qt-5.5.1-android-19
    - cat qt-5.5.1-android-19.env
    - find ${ANDROID_NDK_ROOT} -name arm-linux-androideabi-gcc
    - which arm-linux-androideabi-gcc
    - ls $QT_ROOT
    - source qt-5.5.1-android-19.env
    - which qmake
    - git clone https://github.com/benlau/quickandroid.git
    - cd quickandroid/examples/quickandroidexample
    - qmake
    - make install INSTALL_ROOT=$WORKDIR/build
    - androiddeployqt --output $WORKDIR/build
